### PR TITLE
Add Appraisal

### PR DESCRIPTION
**Pull request by winebarrel**
Add appraisal to be able to test with multiple versions of activesupport.
@hirocaster Could you please review?

### CODE REVIEW

**Comment by hirocaster** [comment]
Which Ruby version are you testing?

**Comment by winebarrel** [comment]
I tested with Ruby 2.3.8.

**Comment by hirocaster** [comment]
I can test Ruby 2.3.8 in my local. It sounds good!
But, appraisal needs over 2.3.x

This lib written under 2.2.x bellow files.
`.ruby-version`, `.travis.yml`

It would be nice if you could modify it to clearly state your intention to work under 2.3.x

**Comment by winebarrel** [comment]
Fixed .travis.yml and .ruby-version 🙏  d0494e1

**Pull request merged**
